### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by PaLeroy**
Try it: `pip install git+http://github.com/moratodpg/imp_marl.git@setup`

### CODE REVIEW

**Comment by moratodpg** [comment]
pip install is working from my end!

**Comment by PaLeroy** [comment]
I think it is working well.

`from imp_marl.imp_wrappers.pettingzoo import pettingzoo_wrap_struct`
`from imp_marl.imp_wrappers.gym import gym_wrap_sa_struct`
`from imp_marl.imp_wrappers.gymnasium import gymnasium_wrap_sa_struct`

**Comment by PaLeroy** [comment]
will do the same for marl_lib and the examples

**Comment by PaLeroy** [comment]
You can also try to execute examples:
`python -m imp_marl.imp_wrappers.gym.examples.random_gym`

**Comment by moratodpg** [comment]
It is working nicely!
image

**Comment by PaLeroy** [comment]
Nice! We merge? :D

**Pull request merged**
