### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by PaLeroy**

### CODE REVIEW

**Comment by PaLeroy** [comment]
First tests on struct_env to start.
Had to change the name of the folder imp_env for docstring compatibility.

Tell me if the tests suit you and if you can think of something else, then we'll proceed quickly.

**Comment by PaLeroy** [comment]
We have now pytest and doctest, the latter will help for documentation I believe!

**Review by moratodpg — COMMENTED** [review]
Great effort @PaLeroy! We got pytests now :). One comment here:

The naming is now a bit confusing -> run_train_; run_test; test... 
One way would be to keep *pymarl mains* as they were `train_with_pymarl` and `test_with_pymarl`. 
We then keep as `pytest` all files related to python tests. What do you think?
That would imply changing `tests` folder to `pytests` and a few additional minor changes.

**Comment by PaLeroy** [comment]
Pytest tracks files starting with "test", so I modified it because test_with_pymarl is not a test.
Afterwards, I added this pytest config file, which may have solved the issue, but I did not try.
Why is it confusing anyway?
Another possibility is to go with pymarl_train and pymarl_test.

For the test folder, I guess everyone just names it "test", I honestly do not care too much.

Would you have any thoughts on the tests themselves?

**Comment by PaLeroy** [comment]
Maybe we accept this PR to have a clean sheet for reorganisation?

**Comment by moratodpg** [comment]
Agreed :)

**Pull request merged**
