### PR TITLE
lint

### PR DESCRIPTION
**Pull request by PaLeroy**
Glad Black makes almost everything automatically 😆

### CODE REVIEW

**Comment by moratodpg** [comment]
This looks very clean and nice now! Great job :)
Shall we conduct a series of tests to ensure everything is working fine?

**Comment by PaLeroy** [comment]
Yeah this is not a bad idea 😄 
Especially because if we wanna go JAX, we will have to write and figure out some tests anyway.

**Comment by moratodpg** [comment]
It seems we might have to re-run this one before merging?

**Comment by PaLeroy** [comment]
re runned.
We may need to go over the files to be sure but it should be ok :D

**Comment by PaLeroy** [comment]
Tests are ok btw.
I went over stuff again and we can merge! :D

**Comment by moratodpg** [comment]
Outstanding! Great work once again, Pascal!
Let's merge it. I am looking forward to getting started with our next steps.

**Pull request merged**
