### PR TITLE
Update citation!

### PR DESCRIPTION
**Pull request by PaLeroy**
We have been accepted :D

### CODE REVIEW

**Comment by moratodpg** [comment]
We could maybe include the poster and slides in the repo. What do you think?

**Comment by PaLeroy** [comment]
Yep.
I was also thinking of changing the repo organisation to separate the paper, and paper results/implementation, from the imp-marl package.
What do you think?

**Comment by PaLeroy** [comment]
Can you please add the typst code of the poster + put them in a dedicated folder?

**Comment by moratodpg** [comment]
Yes, that is a good idea. Let's organize it a bit. 
Could we perhaps merge this PR and open another branch with a more meaningful description? xD

**Pull request merged**
