### PR TITLE
Offshore wind farm initial implementation

### PR DESCRIPTION
**Pull request by moratodpg**
There we go! Initial implementation for an offshore wind farm environment with n_owt turbines. Each wind turbine featuring 3 components at different levels.
Environment and pymarl ma implemented.
Let's check and perhaps also add SARL implementation. :)

### CODE REVIEW

**Comment by PaLeroy** [comment]
Couldn't we have a single pymarl_MA_struct class?
I find that the difference between `struct_env/pymarl_ma_owf.py` and `struct_env/pymarl_ma.py` is very light.
- no alphas
- no correlation
- `n_comp` and `k_comp` replaced by `n_owt` and `lev`

We can have a new param "struct_type" that conditions the list mentioned above.

I will implement it in a different branch so you can see and we discuss it?

**Comment by PaLeroy** [comment]
I'll review this one once the PR of single pymarl_ma file is done*

**Comment by PaLeroy** [comment]
After merging the other PR, we should sync this one with the main before going further.

**Review by PaLeroy — APPROVED** [review]

**Review by moratodpg — COMMENTED** [review]
Excellent work! Some comments:
- Why are we removing 'struct_c_10.yaml? (Not a major issue anyway) :)
Besides that minor comment, I am happy to merge this.
We also keep all 'test_scripts' right?

**Comment by PaLeroy** [comment]
The test scripts are now better organised and all 6 should be executed to check the implementation (if that answer your question :D )

**Review by PaLeroy — APPROVED** [review]

**Pull request merged**
